### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [IanEH/YASFA1#1]
Hi! This project needs a free license to be included in F-Droid :)

I recommend you release it under GPLv3 :)

**Comment by IanEH** [comment]
Hi pizziolo

Hopefully sorted that! Any problems let me know. I have included
"TouchImageView" in the project do not know if that;s a problem? nothing to
do with me but open source and works well, but not critical to the project.
Thought  I would do one that copes with rotation and can be included in
scrolling views some time using different gestures but not got round to it.
Any problems let me know.

Thanks

Ian  E

**Comment by pizzamaker** [comment]
Thanks Ian! Hopefully that'll be enough for the folks at F-Droid to make a stable build.
